lim:
  tcpPort: 9000
  websocketPort: 19000
  bossThreadSize: 1
  workThreadSize: 8
  heartBeatTime: 20000 # Heart beat timeout(milliseconds)心跳超时时间 单位毫秒

  redis:
    mode: single # 单机模式：single 哨兵模式：sentinel 集群模式：cluster
    database: 0
    password: 123456
    timeout: 3000
    poolMinIdle: 8 # Minimum idle number -> 最小空闲数
    poolConnTimeout: 3000 # Connection timeout(milliseconds) -> 连接超时时间(毫秒)
    poolSize: 10 # Redis connection pool size -> 连接池大小
    single: # Single mode configuration -> redis单机配置
      address: 127.0.0.1:6379

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtualHost: /
    userName: guest
    password: guest