plugins {
    id 'java'
    id 'org.springframework.boot' version '2.7.0' // Adjust the version as needed
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
}

group = 'com.zinan'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
//    // RabbitMQ
//    implementation "org.springframework.boot:spring-boot-starter-amqp:${springbootVersion}"
//
//    // Spring Boot Validation
//    implementation 'org.springframework.boot:spring-boot-starter-validation'
//
//    // ZkClient
//    implementation 'com.github.sgroschupf:zkclient'
//
//    // Redis
//    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
//
    // Spring Boot Web
    implementation 'org.springframework.boot:spring-boot-starter-web'
//
//    // Hutool
//    implementation 'cn.hutool:hutool-all'
//
//    // MySQL JDBC Driver
//    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
//    runtimeOnly 'mysql:mysql-connector-java'
//
//    // MyBatis Plus
//    implementation 'com.baomidou:mybatis-plus-boot-starter'
    implementation 'com.github.jeffreyning:mybatisplus-plus:1.5.1-RELEASE'

    implementation project(':im-common')
    // implementation 'com.zinan:codec:1.0.0-SNAPSHOT'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

bootJar {
    enabled = true
}

jar {
    enabled = false
}